### ISSUE TITLE
Porting on Nucleo F446RE ?

### ISSUE THREAD

**Issue by Oconnor24** [beantowel/FFBMK1#1]
Hi Bean,
I create an issue because i would like to contact you but there is no message system on Git.
I'm very interested by your project. I'm trying to build a custom FFB joystick but i already design the hardware and now i'm looking at the electronic/software part of the project.

I'm not a code expert, so can you give me a small rundown on how your code is articulated ?
I'm used to arduino platform but i don't know much about the STM32 family, can you think it will be easy to port your code on the f446re ?It's available as nucleo board and i'll need the CAN bus support to drive my motor.

**Comment by beantowel** [comment]
The core of the FFB stuff was about how to communicate with the host complying the USB PID Class Definition. I thought it was not so hard to migrate the project to other platforms using C. You can focus on these source files: ffb_manager.c, ffb_stick.c, usbd_pid.c. Also the report descriptor in th usbd_hid.c was a decisive factor-i'd advise you don't change the hexadecimal related to ForceFeedback. For this part, you can         refer to my repository HID_Descriptor_tool for more information.
  In brief, make the usb interface functions right(BUS HOUND was recommended for debugging), the rest would be common MCU issues.
I'll soon add some diagram to the README.md to describe the architecture of my code

**Comment by Oconnor24** [comment]
Thanks for the diagram, i'll try to port it over my MCU. I've seen somewhere you're using vJoy to provide some data for the FFB, are you still using this fonction or the code can work as a "standalone" ?

**Comment by beantowel** [comment]
It work as a "standalone". Actually i use the vjoy to build a simulator for debugging when i didn't finish making the hardware (and when i didn't figure out the PID stuff). The advantage of the "simpleFeedWithReceptor" is that it can demonstrate the "force" on each axis, and debugging on PC is more convenient than that on MCU. (I add 2 ugly screenshot to the readme at the moment to show how it looks)

**Comment by Oconnor24** [comment]
Hi bean,
I finally ported your code on a nucleo F103RB, instead of a F446RE. Was way easier to port.
With minor tweak i managed to get it enumerate as a hid device. I'am now looking at the ffb part, but with your stock code (on the ffb side), fedit.exe (and other tools in the "ffbstuff" folder) are unable to detect the device as FFB capable. Any idea ?

On another topic, did you have issue with reading the value from the adc ? i change a bit the code of this part to have a more relevant stick_get_position function (now used for reading adc value and process them), as well as stick_position_calibration ( now used for calibrate the real min/max from the potentiometer). If you're interested on those change tell me , i'll post those on a new fork of your code.

**Comment by beantowel** [comment]
I'm now confused too, the problem is when you were once successfully detected as a FFB device, the registry table will keep a record for you and when you change the code (which then i failed to detected as FFB device on the other computer), it still works on the previous computer. 

The problem i've met with adc is that the stm32CubeMX generated wrong code for the DMA (wrong alignment setting), but i should have fixed it in the code.

I'm busy preparing for the national entrance examination for postgraduate recently, so i can't do much to fix the problems. Anyway, thanks for reviewing the premature codes:)
